apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
    provider: sample-api-server
  name: sample-api-server
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.port }}
    protocol: TCP
  selector:
    app: sample-api-server
  type: ClusterIP
